# -*- coding: utf-8 -*-
"""诛仙(gameId=11) 区服表 —— 从原工具 exe 内嵌数据提取"""

SERVERS = [
    {"server_id": 1, "server": "校园区-天戎"},
    {"server_id": 97, "server": "校园区-御龙"},
    {"server_id": 175, "server": "经典区-仙境奇缘"},
    {"server_id": 16, "server": "经典区-圣音"},
    {"server_id": 9, "server": "经典区-天上人间"},
    {"server_id": 81, "server": "经典区-故乡"},
    {"server_id": 29, "server": "经典区-白鸟"},
    {"server_id": 20, "server": "经典区-秋水"},
    {"server_id": 86, "server": "经典区-逆鳞"},
    {"server_id": 150, "server": "经典区-飞花"},
    {"server_id": 888, "server": "先遣体验服-先知"},
    {"server_id": 822, "server": "变天战区-剑尊鸿威"},
    {"server_id": 581, "server": "变天战区-星耀至尊"},
    {"server_id": 804, "server": "变天战区-烽火流年"},
    {"server_id": 847, "server": "变天战区-碧瑶(电信)"},
    {"server_id": 541, "server": "变天战区-金龙碧海"},
    {"server_id": 513, "server": "变天战区-雷龙耀世"},
    {"server_id": 2008, "server": "幽天战区-九天奇缘"},
    {"server_id": 968, "server": "幽天战区-万里河山"},
    {"server_id": 990, "server": "幽天战区-云龙剑影"},
    {"server_id": 2051, "server": "幽天战区-十载仙梦"},
    {"server_id": 947, "server": "幽天战区-龙战乾坤"},
    {"server_id": 517, "server": "昊天战区-创世绮梦"},
    {"server_id": 821, "server": "昊天战区-碧瑶(网通)"},
    {"server_id": 2079, "server": "昊天战区-雪琪"},
    {"server_id": 519, "server": "昊天战区-龙腾碧霄"},
    {"server_id": 587, "server": "朱天战区-万毒弥天"},
    {"server_id": 583, "server": "朱天战区-万毒行疆"},
    {"server_id": 803, "server": "朱天战区-瀚海潮歌"},
    {"server_id": 811, "server": "朱天战区-蚀骨问道"},
    {"server_id": 2088, "server": "朱天战区-剑啸清风"},
    {"server_id": 984, "server": "炎天战区-三界凡尘"},
    {"server_id": 2027, "server": "炎天战区-夜羽凰踪"},
    {"server_id": 590, "server": "炎天战区-山海苍龙"},
    {"server_id": 531, "server": "炎天战区-幻月冰心"},
    {"server_id": 2060, "server": "炎天战区-沧海琼音"},
    {"server_id": 591, "server": "炎天战区-瑞龙惊涛"},
    {"server_id": 525, "server": "炎天战区-瑶梦故城"},
    {"server_id": 502, "server": "苍天战区-幻月御风"},
    {"server_id": 550, "server": "苍天战区-承天问影"},
    {"server_id": 527, "server": "苍天战区-紫电荣光"},
    {"server_id": 507, "server": "苍天战区-霜雪玉龙"},
    {"server_id": 2025, "server": "钧天战区-万法归元"},
    {"server_id": 557, "server": "钧天战区-天地四方"},
    {"server_id": 563, "server": "钧天战区-天帝宝库"},
    {"server_id": 545, "server": "钧天战区-皓月长生"},
    {"server_id": 579, "server": "钧天战区-神剑临霜"},
    {"server_id": 802, "server": "钧天战区-青霄剑鸣"},
    {"server_id": 586, "server": "钧天战区-黄沙百战"},
    {"server_id": 2064, "server": "阳天战区-决胜风云"},
    {"server_id": 2065, "server": "阳天战区-月舞江南"},
    {"server_id": 554, "server": "阳天战区-独霸天关"},
    {"server_id": 546, "server": "扶风战区-小竹峰"},
]

# server_id -> server
ID2NAME = {s['server_id']: s['server'] for s in SERVERS}
# server -> server_id
NAME2ID = {s['server']: s['server_id'] for s in SERVERS}
